DROP TABLE IF EXISTS blacklists CASCADE;

CREATE TABLE blacklists
(
  id          SERIAL  PRIMARY KEY,

  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  website_id  INTEGER NOT NULL REFERENCES websites(id) ON DELETE CASCADE
)
